### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by mzafarr** [Aryan9592/DEX-Dapp#1]
Hi there! I hope you're doing well. I found you in the contributors list of quivr on GitHub, I am creating a project similar to it, today I found quivr, It has all the features I want with addition of many extras I need someone to help me understand at least some parts of the codebase so I can make required changes. 
thank you.
you can delete this issue after reading it. contact: zafarr.pk@gmail.com

**Comment by 0xScratch** [comment]
Hey @mzafarr , The contributions I made were just some documentation changes...nothing particular in codebase. 
Try contacting this guy -> https://github.com/StanGirard

**Comment by mzafarr** [comment]
Do you think he will be willing to help or is it just because he's one of the top contributors?

**Comment by 0xScratch** [comment]
I guess yeah, tho he might be busy..you could ask him for his social media id (either discord or something). and he probably gonna know most of the stuff about this repo. 
Still, don't rely on him for every of your doubt. Cuz it's obvious he won't be having time for every of your question..Thus, also try seeking help from AI
